/* Lua5.1.dll -> Lua51.dll Functions forwarder */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>


#ifdef _MSC_VER
#define FORWARD(func) \
	__pragma(comment(linker, "/export:" #func "=lua51." #func))
#else
#error Unsupported compiler
#endif

FORWARD(luaL_addlstring)
FORWARD(luaL_addlstring)
FORWARD(luaL_addstring)
FORWARD(luaL_addvalue)
FORWARD(luaL_argerror)
FORWARD(luaL_buffinit)
FORWARD(luaL_callmeta)
FORWARD(luaL_checkany)
FORWARD(luaL_checkinteger)
FORWARD(luaL_checklstring)
FORWARD(luaL_checknumber)
FORWARD(luaL_checkoption)
FORWARD(luaL_checkstack)
FORWARD(luaL_checktype)
FORWARD(luaL_checkudata)
FORWARD(luaL_error)
FORWARD(luaL_findtable)
FORWARD(luaL_getmetafield)
FORWARD(luaL_gsub)
FORWARD(luaL_loadbuffer)
FORWARD(luaL_loadfile)
FORWARD(luaL_loadstring)
FORWARD(luaL_newmetatable)
FORWARD(luaL_newstate)
FORWARD(luaL_openlib)
FORWARD(luaL_openlibs)
FORWARD(luaL_optinteger)
FORWARD(luaL_optlstring)
FORWARD(luaL_optnumber)
FORWARD(luaL_prepbuffer)
FORWARD(luaL_pushresult)
FORWARD(luaL_ref)
FORWARD(luaL_register)
FORWARD(luaL_typerror)
FORWARD(luaL_unref)
FORWARD(luaL_where)
FORWARD(lua_atpanic)
FORWARD(lua_call)
FORWARD(lua_checkstack)
FORWARD(lua_close)
FORWARD(lua_concat)
FORWARD(lua_cpcall)
FORWARD(lua_createtable)
FORWARD(lua_dump)
FORWARD(lua_equal)
FORWARD(lua_error)
FORWARD(lua_gc)
FORWARD(lua_getallocf)
FORWARD(lua_getfenv)
FORWARD(lua_getfield)
FORWARD(lua_gethook)
FORWARD(lua_gethookcount)
FORWARD(lua_gethookmask)
FORWARD(lua_getinfo)
FORWARD(lua_getlocal)
FORWARD(lua_getmetatable)
FORWARD(lua_getstack)
FORWARD(lua_gettable)
FORWARD(lua_gettop)
FORWARD(lua_getupvalue)
FORWARD(lua_insert)
FORWARD(lua_iscfunction)
FORWARD(lua_isnumber)
FORWARD(lua_isstring)
FORWARD(lua_isuserdata)
FORWARD(lua_lessthan)
FORWARD(lua_load)
FORWARD(lua_newstate)
FORWARD(lua_newthread)
FORWARD(lua_newuserdata)
FORWARD(lua_next)
FORWARD(lua_objlen)
FORWARD(lua_pcall)
FORWARD(lua_pushboolean)
FORWARD(lua_pushcclosure)
FORWARD(lua_pushfstring)
FORWARD(lua_pushinteger)
FORWARD(lua_pushlightuserdata)
FORWARD(lua_pushlstring)
FORWARD(lua_pushnil)
FORWARD(lua_pushnumber)
FORWARD(lua_pushstring)
FORWARD(lua_pushthread)
FORWARD(lua_pushvalue)
FORWARD(lua_pushvfstring)
FORWARD(lua_rawequal)
FORWARD(lua_rawget)
FORWARD(lua_rawgeti)
FORWARD(lua_rawset)
FORWARD(lua_rawseti)
FORWARD(lua_remove)
FORWARD(lua_replace)
FORWARD(lua_resume)
FORWARD(lua_setallocf)
FORWARD(lua_setfenv)
FORWARD(lua_setfield)
FORWARD(lua_sethook)
FORWARD(lua_setlocal)
FORWARD(lua_setmetatable)
FORWARD(lua_settable)
FORWARD(lua_settop)
FORWARD(lua_setupvalue)
FORWARD(lua_status)
FORWARD(lua_toboolean)
FORWARD(lua_tocfunction)
FORWARD(lua_tointeger)
FORWARD(lua_tolstring)
FORWARD(lua_tonumber)
FORWARD(lua_topointer)
FORWARD(lua_tothread)
FORWARD(lua_touserdata)
FORWARD(lua_type)
FORWARD(lua_typename)
FORWARD(lua_xmove)
FORWARD(lua_yield)
FORWARD(luaopen_base)
FORWARD(luaopen_debug)
FORWARD(luaopen_io)
FORWARD(luaopen_math)
FORWARD(luaopen_os)
FORWARD(luaopen_package)
FORWARD(luaopen_string)
FORWARD(luaopen_table)


BOOL WINAPI
DllMain(HINSTANCE hinst, DWORD reason, LPVOID reserved)
{
  (void) reserved;
  if (reason == DLL_PROCESS_ATTACH)
    DisableThreadLibraryCalls(hinst);
  return 1;
}

BOOL WINAPI
_DllMainCRTStartup(HINSTANCE hinst, DWORD reason, LPVOID reserved)
{
  return DllMain(hinst, reason, reserved);
}
